// Tap detection and highlight images for the game scene.
//
// Every tappable thing is a designer cut-out: GREEN ones are hazards, RED ones are everything
// else. When a thing is tapped, its cut-out is drawn over the scene.
//
// scene-labels.png (same size as the scene) says which thing each pixel belongs to
// (id = red * 256 + green, 0 = nothing). Tap areas are the cut-outs with small gaps filled in,
// so a tap between the pipes of the refinery still finds the refinery. scene-objects.json
// lists each id: its cut-out key, kind ('hazard' | 'object') and where the cut-out is drawn.
// Both are generated by tools/scene/build_objects.py.
//
// Which scene's assets these functions read is set by loadSceneMap(scene) (see data/scenes.js
// for the scene descriptors) — the admin dashboard picks the active scene at runtime.
export let OBJECTS = new Map()

let activeScene = null
let imageFor = () => undefined
let labels = null // Uint16Array, one id per scene pixel
let width = 0
let height = 0
let loading = null

// fetch() can't load file:// URLs in a packaged build (Chromium blocks it for local files),
// so the labels image is loaded as a normal <img> instead — that works under file:// too.
function loadImage(url) {
  return new Promise((resolve, reject) => {
    const img = new Image()
    img.onload = () => resolve(img)
    img.onerror = () => reject(new Error(`Could not load ${url}`))
    img.src = url
  })
}

export function loadSceneMap(scene) {
  if (activeScene !== scene) {
    // switching scene: drop whatever was loaded for the previous one and start over
    activeScene = scene
    imageFor = scene.imageFor
    OBJECTS = new Map(scene.objectList.map((o) => [o.id, o]))
    labels = null
    loading = null
  }
  if (!loading) {
    loading = (async () => {
      const img = await loadImage(scene.labelsUrl)
      // no colour management or premultiplying: the pixel values are ids, not colours
      const bmp = await createImageBitmap(img, {
        colorSpaceConversion: 'none',
        premultiplyAlpha: 'none'
      })
      const canvas = new OffscreenCanvas(bmp.width, bmp.height)
      const ctx = canvas.getContext('2d', { willReadFrequently: true })
      ctx.drawImage(bmp, 0, 0)
      const rgba = ctx.getImageData(0, 0, bmp.width, bmp.height).data
      const ids = new Uint16Array(bmp.width * bmp.height)
      for (let i = 0, p = 0; i < ids.length; i++, p += 4) ids[i] = (rgba[p] << 8) | rgba[p + 1]
      width = bmp.width
      height = bmp.height
      labels = ids
      bmp.close()
    })().catch((err) => {
      loading = null // allow a retry
      throw err
    })
  }
  return loading
}

const idAt = (x, y) =>
  x < 0 || y < 0 || x >= width || y >= height ? 0 : labels[(y | 0) * width + (x | 0)]

// What did a tap at (fx, fy) — fractions of the scene's width/height — land on?
// A hazard within `tolerancePx` scene pixels wins over anything else, so a slightly-off tap on
// a thin hazard (a ladder, a hose) still counts. Returns an object entry or null.
export function hitTest(fx, fy, tolerancePx = 14) {
  if (!labels) return null
  const x = fx * width
  const y = fy * height
  const direct = OBJECTS.get(idAt(x, y))
  if (direct?.kind === 'hazard') return direct

  let best = null
  let bestD = Infinity
  const step = 2
  for (let dy = -tolerancePx; dy <= tolerancePx; dy += step) {
    for (let dx = -tolerancePx; dx <= tolerancePx; dx += step) {
      const d = dx * dx + dy * dy
      if (d > tolerancePx * tolerancePx || d >= bestD) continue
      const o = OBJECTS.get(idAt(x + dx, y + dy))
      if (o?.kind === 'hazard') {
        best = o
        bestD = d
      }
    }
  }
  return best || direct || null
}

// The tinted cut-out for an object and where to draw it, as percentages of the scene.
export function highlightFor(id) {
  const o = OBJECTS.get(id)
  if (!o || !width) return null
  return {
    src: imageFor(o.key),
    style: {
      left: `${(o.x / width) * 100}%`,
      top: `${(o.y / height) * 100}%`,
      width: `${(o.w / width) * 100}%`,
      height: `${(o.h / height) * 100}%`
    }
  }
}

export const idForKey = (key) => activeScene?.objectList.find((o) => o.key === key)?.id
